version: '3'

services:
  wordpress:
    image: conetix/wordpress-with-wp-cli
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${RDSPrimaryDB.Endpoint.Address}:3306
      WORDPRESS_DB_USER: ${RDSDBUser}
      WORDPRESS_DB_PASSWORD: ${RDSDBPassword}
      WORDPRESS_DB_NAME: ${RDSDBName}